### ISSUE TITLE
Go version  (1.18 or 1.18.2) invalid use of type alias  FnSwitchOnFirst in recursive type (see issue #50729)

### ISSUE THREAD

**Issue by reddyhc** [jjeffcaii/reactor-go#39]
Using go version 1.18 or 1.18.1, seeing the compilation error on recursive type  error ,  not seeing this issue in go lang versions 1.17.9 or older.

**invalid use of type alias FnSwitchOnFirst in recursive type** in file file types.go under flux pkg.

Please refer to issue which is in open state : https://github.com/golang/go/issues/50729

**Comment by MrDienns** [comment]
I'm also facing this issue. Any progress on this? @reddyhc did you find any workaround?

**Comment by jjeffcaii** [comment]
@reddyhc Thanks for the PR https://github.com/jjeffcaii/reactor-go/pull/40

**Comment by jjeffcaii** [comment]
Hi, all~ The #40 has been merged and released with v0.5.3. Thanks.
